### PR TITLE
v2.1.0 - Added `no-else-return` rule 

### PR DESCRIPTION
**Pull request by bulutcy**
- Added `no-else-return` rule to release restrictions on if-else statements. It was causing a bug when auto fix is correcting the code.

### CODE REVIEW

**Comment by ashleynolan** [comment]
@bulutcy Looks like the tests are failing for some reason – worth running locally as may need to change the test cases with this rule addition.

**Comment by DamianMullins** [comment]
@ashleynolan I looked into this earlier and the issue is [coming from the `prelint` task](https://github.com/justeat/eslint-config-fozzie/blob/0b22723ab71a14bb41e741c290a962d7ad685866/package.json#L7). Running locally everything is fine, any ideas?

**Comment by ashleynolan** [comment]
Just checked it out – there's whitespace at the end of line 29 in the `best-practices.js` which is why this is failing the build.

@bulutcy As this is a PR from a fork, I can't push the change – can you make this change and push it up?

**Comment by DamianMullins** [comment]
@ashleynolan So this repo enforces no newlines at the end of files? 😱

**Pull request merged**
